# -*- coding: utf-8 -*-
"""task4_visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xC7RL-MXMcbV7XS13G-oW5PW8HL2HloW
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

df = pd.read_csv("/content/trends_analysed.csv")

if not os.path.exists("outputs"):
    os.mkdir("outputs")

top10 = df.sort_values(by="score", ascending=False).head(10)

titles = top10["title"].apply(lambda x: x[:50])
scores = top10["score"]

plt.figure()
plt.barh(titles, scores)
plt.xlabel("Score")
plt.ylabel("Title")
plt.title("Top 10 Stories by Score")

plt.savefig("outputs/chart1_top_stories.png")
plt.show()

counts = df["category"].value_counts()

plt.figure()
plt.bar(counts.index, counts.values)
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

plt.savefig("outputs/chart2_categories.png")
plt.show()

popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.figure()
plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

plt.xlabel("Score")
plt.ylabel("Comments")
plt.title("Score vs Comments")
plt.legend()

plt.savefig("outputs/chart3_scatter.png")
plt.show()

fig, axs = plt.subplots(1, 3, figsize=(15, 5))

# Chart 1
axs[0].barh(titles, scores)
axs[0].set_title("Top Stories")

# Chart 2
axs[1].bar(counts.index, counts.values)
axs[1].set_title("Categories")

# Chart 3
axs[2].scatter(popular["score"], popular["num_comments"])
axs[2].scatter(not_popular["score"], not_popular["num_comments"])
axs[2].set_title("Score vs Comments")

plt.suptitle("TrendPulse Dashboard")

plt.savefig("outputs/dashboard.png")
plt.show()