# -*- coding: utf-8 -*-
"""task_1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bil6Ee2ysegxngbUnbQRtzuaPSLy9UxS
"""

import pandas as pd
import requests
import time

headers = {"User-Agent": "TrendPulse/1.0"}

url=" https://hacker-news.firebaseio.com/v0/topstories.json"
response=requests.get(url ,headers=headers)

if response.status_code!=200:
  print("faild to fetch story ids")
  exit()
ids=response.json()[:500]

categorys={
    "technology":["ai","tech","software"],
    "sports":["nfl","nba","game"]
}

results=[]
for category,keyword in categorys.items():
  count=0
  for sid in ids:
    if count >= 25 :
      break
    try:
        item_url="https://hacker-news.firebaseio.com/v0/item/{sid}.json"
        res=requests.get(item_url,headers=headers)
        if res.status_code != 200:
          print(f"faild to fetch{sid}")
          continue
        data = res.json()
        if data is None:
           continue
        title = data.get("title", "").lower()
        if not title:
                continue

        print(data)

        if any(word in title for word in keywords):
          story={
              "post_id":data.get("id"),
              "title":data.get("title"),
              "category":category
              }

          results.append(story)
          count+=1
    except Exception as e:
            print(f"Error for ID {sid}: {e}")
            continue

time.sleep(2)
print(results)

from datetime import datetime
categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

results = []


for category, keywords in categories.items():

    count = 0

    for sid in ids:

        if count >= 25:
            break

        try:
            item_url = f"https://hacker-news.firebaseio.com/v0/item/{sid}.json"
            res = requests.get(item_url, headers=headers)

            if res.status_code != 200:
                print(f"Failed ID {sid}")
                continue

            data = res.json()

            if data is None:
                continue

            title = data.get("title")

            if not title:
                continue

            title_lower = title.lower()

            if any(word in title_lower for word in keywords):

                current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

                story = {
                    "post_id": data.get("id"),
                    "title": title,
                    "category": category,
                    "score": data.get("score", 0),
                    "num_comments": data.get("descendants", 0),
                    "author": data.get("by", "unknown"),
                    "collected_at": current_time
                }

                results.append(story)
                count += 1

                print(story)
        except Exception as e:
            print(f"Error {sid}: {e}")
            continue
    import time
    time.sleep(2)
print(f"Total collected: {len(results)}")

import os
import json
from datetime import datetime

if not os.path.exists("data"):
    os.mkdir("data")

today = datetime.now().strftime("%Y%m%d")
filename = "data/trends_" + today + ".json"

file = open(filename, "w")
json.dump(results, file, indent=4)
file.close()

print("Collected", len(results), "stories.")
print("Saved to", filename)