# -*- coding: utf-8 -*-
"""task3_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ukJzwhEu4FEvDQunuq2DtNXKDBE_AHr
"""

import numpy as np
import pandas as pd
df=pd.read_csv("/content/trends_clean.csv")
print("Loaded data:", df.shape)
print("\nFirst 5 rows:")
print(df.head())
print("\nAverage score:", int(df["score"].mean()))
print

scores = df["score"].values
comments = df["num_comments"].values

print("\nNumPy Stats")
print("Mean score:", int(np.mean(scores)))
print("Median score:", int(np.median(scores)))
print("Std deviation:", int(np.std(scores)))

print("Max score:", np.max(scores))
print("Min score:", np.min(scores))

category_counts = df["category"].value_counts()

top_category = category_counts.idxmax()
top_count = category_counts.max()

print("\nMost stories in:", top_category, f"({top_count} stories)")

row = df.loc[df["num_comments"].idxmax()]

print("\nMost commented story:")
print(f'"{row["title"]}" — {row["num_comments"]} comments')

df["engagement"] = df["num_comments"] / (df["score"] + 1)

avg_score = df["score"].mean()
df["is_popular"] = df["score"] > avg_score
df.head()

import os

if not os.path.exists("data"):
    os.mkdir("data")

df.to_csv("data/trends_analysed.csv", index=False)

print("Saved to data/trends_analysed.csv")