# -*- coding: utf-8 -*-
"""task_2_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P11_KrvI0vYY7A3H0HqS8eGvNsoHz9g9
"""

import pandas as pd

df = pd.read_json("trends_20260406.json")

print("Loaded", len(df), "stories")

df = df.drop_duplicates(subset="post_id")
print("After removing duplicates:", len(df))

df = df.dropna(subset=["post_id", "title", "score"])
print("After removing nulls:", len(df))

df = df[df["score"] >= 5]
print("After removing low scores:", len(df))

import os

if not os.path.exists("data"):
    os.mkdir("data")

df.to_csv("data/trends_clean.csv", index=False)

print("Saved", len(df), "rows to data/trends_clean.csv")

print("\nStories per category:")
print(df["category"].value_counts())